### ISSUE TITLE
MessageLogger logs source wrong

### ISSUE THREAD

**Issue by VoltaicRainbow** [VoltaicRainbow/WalkingSim2#1]
It appears to log the destination of a message.

`973288021228 [Timer] init_system {} `
`973288021238 [Console] init_system {}`
`973288021691 [Renderer] init_system {} `

Should it not mark as [Main] ?

**Comment by mlajszczak** [comment]
It's a bug. It should be [Main].

**Comment by mlajszczak** [comment]
Nah, it's correct. Message log logs processed messages (with processing timestamp). Every destination system processes messages at its own pace and we want to keep track of that.
